export const caseStudies = [
  {
    slug: 'real-estate-automation-demo',
    title: 'Real Estate Lead Management & Automation Platform',
    status: 'illustrative',
    industry: 'Real Estate',
    market: 'UAE',
    summary: 'Centralised CRM + real estate management for a growing brokerage handling enquiries via spreadsheets and messaging apps.',
    challenge: 'Enquiries from portal + site + WhatsApp scattered; assignment ad-hoc; follow-ups slipped; reporting manual.',
    requirements: ['Lead capture & inbox', 'Property management', 'Agent assignment', 'Follow-ups & reminders', 'Dashboard & reports', 'WhatsApp & site integration'],
    solution: 'Centralised CRM + Real Estate ERP with lead inbox, scoring, listing, assignment, dashboard and role-based access.',
    architecture: 'Website → API → CRM → Postgres → AI qualification → notifications → dashboard',
    features: ['Lead scoring', 'Property listings', 'Assignment', 'Reminders', 'Reporting', 'Roles', 'WhatsApp concept', 'Site lead integration'],
    workflow: 'Portal → CRM → AI qualifies → assign → visit → follow-up → booking → commission',
    technology: ['Next.js', 'Node.js', 'PostgreSQL', 'REST APIs'],
    process: ['Discovery', 'Module map', 'Build', 'Integrate', 'Launch'],
    outcomes: 'Illustrative benefit: better visibility, reduced admin and more consistent follow-up. No fake numeric claims.',
    faq: [{ q: 'Is this a real client?', a: 'No — labelled Illustrative Case Study — Demo Concept until permission is granted.' }],
  },
  {
    slug: 'ai-customer-support-demo',
    title: 'AI Customer Support Agent for a Growing Business',
    status: 'illustrative',
    industry: 'Professional Services',
    market: 'USA',
    summary: 'AI assistant integrated with knowledge base and escalation for a US SME with multi-channel questions.',
    challenge: 'Questions arrived via web, email and phone; team repeated answers; escalation was informal.',
    requirements: ['FAQ handling', 'Knowledge retrieval', 'Qualification', 'Escalation', 'History & analytics'],
    solution: 'RAG agent with tool-calling, confidence threshold and human escalation, logging to CRM.',
    architecture: 'Message → LLM → Vector retrieval → tools → human approval → CRM → analytics',
    features: ['Grounded answers', 'Qualification', 'Escalation', 'History', 'Analytics'],
    workflow: 'Question → retrieval → answer/escalate → CRM log → review',
    technology: ['LLM APIs', 'Vector Search', 'Next.js', 'Node.js'],
    process: ['Discover', 'Ingest knowledge', 'Build', 'Test', 'Launch'],
    outcomes: 'Illustrative outcome: reduced repetitive workload and improved consistency.',
    faq: [{ q: 'Fully autonomous?', a: 'No — scoped permissions with human escalation.' }],
  },
  {
    slug: 'school-management-demo',
    title: 'School Management & Parent Communication Platform',
    status: 'illustrative',
    industry: 'Education',
    market: 'UK',
    summary: 'Multi-module school platform for admissions, fees, attendance and parent comms for a UK school group concept.',
    challenge: 'Paper-led admissions/fees/attendance; parents lacked visibility; reports slow.',
    requirements: ['Admissions', 'Student records', 'Fees', 'Attendance', 'Reports', 'Notifications'],
    solution: 'School ERP with parent portal and role-aware dashboards.',
    architecture: 'Web → API → ERP → Postgres → notifications',
    features: ['Admissions', 'Fees', 'Attendance', 'Parent portal', 'Reports'],
    workflow: 'Enquiry → admission → student record → fee schedule → attendance → comms',
    technology: ['Next.js', 'Node.js', 'PostgreSQL'],
    process: ['Map flow', 'Build', 'Import', 'Train', 'Go-live'],
    outcomes: 'Illustrative benefit: centralised operations and information visibility.',
    faq: [],
  },
  {
    slug: 'business-automation-demo',
    title: 'AI-Powered Internal Business Automation System',
    status: 'illustrative',
    industry: 'Professional Services',
    market: 'USA',
    summary: 'Internal automation: form → AI classification → CRM → task → notification → dashboard.',
    challenge: 'Manual handoffs between form, CRM and task tools; SLA breaches; no audit.',
    requirements: ['Classification', 'CRM update', 'Task creation', 'Notification', 'Dashboard'],
    solution: 'Workflow automation with AI classification, rules and human checkpoints.',
    architecture: 'Form → workers → AI → rules → CRM/tasks → dashboard',
    features: ['AI classification', 'Tasking', 'Notifications', 'Logs'],
    workflow: 'Submission → classification → CRM → task → notify → dashboard',
    technology: ['Node.js', 'PostgreSQL', 'Webhooks'],
    process: ['Map', 'Build', 'Test', 'Launch'],
    outcomes: 'Illustrative benefit: faster handoff and traceable audit trail.',
    faq: [],
  },
  {
    slug: 'custom-erp-demo',
    title: 'Custom Business ERP Platform',
    status: 'illustrative',
    industry: 'SME',
    market: 'UAE',
    summary: 'Modular ERP for a UAE SME: inventory, sales, purchasing, finance, employees and reporting.',
    challenge: 'Ops data siloed; reconciliation manual; permissions coarse.',
    requirements: ['Inventory', 'Sales', 'Purchasing', 'Finance', 'Employees', 'Reports'],
    solution: 'Modular ERP with fine-grained permissions and dashboards.',
    architecture: 'Apps → API → ERP core → Postgres → reports',
    features: ['Modules', 'Permissions', 'Reports', 'Imports'],
    workflow: 'Order → inventory → finance → report',
    technology: ['Next.js', 'Node.js', 'PostgreSQL'],
    process: ['Discovery', 'Map modules', 'Build', 'Rollout'],
    outcomes: 'Illustrative benefit: single source of truth for operations.',
    faq: [],
  },
];

export function getCaseStudy(slug) {
  return caseStudies.find((c) => c.slug === slug) || null;
}
