export const globalFaqs = [
  { q: 'What does AiOpsMedia build?', a: 'We design and build AI, software and automation: portals, dashboards, CRM/ERP, AI agents, internal tools, SaaS, integrations and e-commerce.' },
  { q: 'Do you work with US businesses?', a: 'Yes — remotely from India with US-friendly overlap, transparent pricing and code ownership. See /usa.' },
  { q: 'Do you work with UK businesses?', a: 'Yes — GMT/BST overlap and British English on UK pages. See /uk.' },
  { q: 'Do you work with Dubai/UAE businesses?', a: 'Yes — Dubai, Abu Dhabi, Sharjah and across the UAE remotely. No fake office claimed. See /uae and /uae/dubai.' },
  { q: 'Can you build custom CRM software?', a: 'Yes — modeled on your pipeline with leads, tasks, permissions, reports, integrations and AI scoring. /services/crm-development' },
  { q: 'Can you build AI agents?', a: 'Yes — knowledge-grounded agents with tools, memory and human escalation. /services/ai-agents' },
  { q: 'Can you integrate AI into existing business?', a: 'Yes — RAG, copilots and automation added to your current stack via APIs.' },
  { q: 'How much does custom software cost?', a: 'Custom pricing based on scope, complexity, integrations, AI, users, design and maintenance. We give a staged estimate after discovery.' },
  { q: 'How long does a software project take?', a: 'Small 4–8 weeks, mid 8–16 weeks, complex ERP/SaaS 3–6 months+ — staged delivery.' },
  { q: 'Do you provide ongoing maintenance?', a: 'Yes — hosting, updates, security, monitoring and iterative improvement.' },
  { q: 'Can you migrate from spreadsheets?', a: 'Yes — import, dedupe and phased cutover without stopping the business.' },
  { q: 'Can you integrate WhatsApp/payment systems?', a: 'WhatsApp Business and payment gateway concepts, compliant with platform policies.' },
  { q: 'Do you work remotely?', a: 'Yes — we operate from India and serve international clients remotely with clear comms and weekly reviews.' },
];
