export const industries = [
  {
    slug: 'real-estate',
    title: 'Real Estate',
    short: 'Leads → visits → bookings → commissions in one place.',
    seoTitle: 'Real Estate Software Development | CRM & ERP | AiOpsMedia',
    seoDescription: 'Real estate tech: lead capture, property management, agent assignment, site visits, bookings, commissions and automation for Dubai/UAE and global brokers.',
    problem: 'Leads from portals, website and WhatsApp scatter; assignments fail; follow-ups slip; reporting is guesswork.',
    solutions: ['Unified lead inbox & scoring', 'Property & inventory module', 'Agent assignment & velocity tracking', 'Site visit scheduling & automation', 'Booking/payments/commissions & reports'],
    ai: ['AI lead qualification and routing', 'Property matching', 'Follow-up drafting', 'Document extraction'],
    automation: ['Portal → CRM → assignment → reminder', 'Post-visit follow-up sequence', 'Commission calc & payout log'],
    crmErp: ['Real Estate ERP modules and RealEstate CRM: see /services/real-estate-erp'],
    features: ['Role permissions', 'WhatsApp & site integration', 'Dashboards & permissions'],
    workflow: ['Portal enquiry → CRM → AI qualifies → agent assigned → visit booked → follow-up → booking → commission'],
    process: ['Discovery', 'Module map', 'Build', 'Integrate', 'Launch'],
    cta: 'Talk Real Estate Tech',
  },
  {
    slug: 'education',
    title: 'Education',
    short: 'Admissions, fees, attendance and parent comms.',
    seoTitle: 'Education Software & School ERP | AiOpsMedia',
    seoDescription: 'School ERP and education automation: admissions, student records, fees, attendance and parent communication.',
    problem: 'Admissions, fees, attendance and parent updates stretch staff across paper and disjoint tools.',
    solutions: ['Digital admissions & enquiries', 'Student records & fee tracking', 'Attendance & timetables', 'Parent portal & notifications', 'Analytics & reports'],
    ai: ['AI-assisted enquiry handling', 'Knowledge copilot for staff', 'Fee/attendance insights'],
    automation: ['Enquiry → CRM → counselor assignment', 'Fee due → reminder → receipt', 'Attendance → parent notification'],
    crmErp: ['School ERP: /services/school-erp'],
    features: ['Branch-aware', 'Role-based', 'Reports & exports'],
    workflow: ['Enquiry → qualification → admission → student record → fee schedule → attendance tracking'],
    process: ['Map school flow', 'Configure modules', 'Import data', 'Train', 'Go-live'],
    cta: 'Explore Education Tech',
  },
  {
    slug: 'healthcare',
    title: 'Healthcare',
    short: 'Admin workflows, not clinical decisions.',
    seoTitle: 'Healthcare Software Development | CRM & Automation | AiOpsMedia',
    seoDescription: 'Appointment workflows, CRM, patient communication, administrative automation and dashboards — software does not replace clinicians.',
    problem: 'Appointments, communications and document workflows overwhelm front-office teams.',
    solutions: ['Appointment scheduling & reminders', 'CRM for patient admin comms', 'Document intake & extraction', 'Dashboards & reports'],
    ai: ['AI triage for FAQs (with human review)', 'Document classification'],
    automation: ['Booking → reminder → check-in → follow-up', 'Form → record → task'],
    crmErp: ['Custom CRM + automation; no clinical claims'],
    features: ['Permissions & audit', 'Integrations', 'Comms templates'],
    workflow: ['Inquiry → appointment → reminder → visit → document → follow-up'],
    process: ['Discovery', 'Design', 'Build', 'Test', 'Launch'],
    cta: 'Discuss Healthcare Ops',
    disclaimer: 'Software supports administrative workflows. It does not replace qualified healthcare professionals or provide medical advice.',
  },
  {
    slug: 'ecommerce',
    title: 'E-commerce',
    short: 'Catalog to cash, integrated.',
    seoTitle: 'E-commerce Software Development | Stores & Automation | AiOpsMedia',
    seoDescription: 'E-commerce development, inventory sync, payments and CRM/ERP integration for scalable retail.',
    problem: 'Catalog, cart, payments and inventory disconnect; promo/reporting gaps hurt growth.',
    solutions: ['Headless or classic storefront', 'Cart, checkout & payments', 'Inventory & order sync', 'CRM/ERP & analytics'],
    ai: ['Recommendation & search', 'Support copilot', 'Demand insights'],
    automation: ['Order → inventory → fulfilment → notification', 'Abandoned cart → recovery sequence'],
    crmErp: ['E-commerce + CRM/ERP integration: /services/ecommerce-development'],
    features: ['Promos & reviews', 'Role access', 'Reports'],
    workflow: ['Catalog → cart → checkout → payment → fulfilment → support'],
    process: ['Strategy', 'Build', 'Integrate', 'Launch', 'Optimize'],
    cta: 'Build Your Store',
  },
  {
    slug: 'hospitality',
    title: 'Hospitality',
    short: 'Bookings, operations and guest comms.',
    seoTitle: 'Hospitality Software & Automation | AiOpsMedia',
    seoDescription: 'Hospitality tech: bookings, inventory, housekeeping workflows and automation for hotels and services.',
    problem: 'Bookings, housekeeping and guest comms run on chat and sheets; visibility lags.',
    solutions: ['Booking & inventory', 'Housekeeping workflows', 'Guest comms & notifications', 'Reports'],
    ai: ['Demand forecasting', 'Guest FAQ copilot'],
    automation: ['Booking → confirmation → housekeeping task → feedback request'],
    crmErp: ['Hospitality ERP concepts'],
    features: ['Calendar & channel concepts', 'Permissions', 'Dashboard'],
    workflow: ['Inquiry → booking → operations → guest comms → review'],
    process: ['Map flow', 'Build', 'Integrate', 'Launch'],
    cta: 'Automate Hospitality',
  },
  {
    slug: 'professional-services',
    title: 'Professional Services',
    short: 'From spreadsheet to scale.',
    seoTitle: 'Software for Professional Services | AiOpsMedia',
    seoDescription: 'Software for agencies, consultants and firms: CRM, projects, timesheets, invoicing and automation.',
    problem: 'Projects, timesheets and invoicing live in spreadsheets; deadlines slip; margins unknown.',
    solutions: ['Project & task management', 'Timesheets & billing', 'CRM pipeline', 'Dashboards'],
    ai: ['Proposal drafting', 'Meeting summarisation', 'Forecasting'],
    automation: ['Lead → proposal → project → invoice → reminder'],
    crmErp: ['CRM + Projects + Invoices integrated'],
    features: ['Roles & approvals', 'Reports', 'Integrations'],
    workflow: ['Lead → proposal → planning → execution → billing'],
    process: ['Discover', 'Build', 'Test', 'Launch'],
    cta: 'Transform Your Firm',
  },
  {
    slug: 'startups',
    title: 'Startups',
    short: 'MVP to scale without rebuild.',
    seoTitle: 'Software for Startups | MVP & SaaS Development | AiOpsMedia',
    seoDescription: 'Startup software: MVPs, SaaS, dashboards and AI — built to learn fast and scale.',
    problem: 'Need speed to market, but duct-tapeMVP hurts fundraising and scaling.',
    solutions: ['Clickable prototype', 'MVP with real stack', 'Scale roadmap & architecture'],
    ai: ['AI features that delight early users', 'Knowledge tools'],
    automation: ['Signup → onboarding → activation → feedback'],
    crmErp: ['Light CRM + analytics from day one'],
    features: ['Weekly sprints', 'Code ownership', 'Cloud-ready'],
    workflow: ['Idea → prototype → MVP → traction → scale'],
    process: ['Discover', 'Prototype', 'Build', 'Launch', 'Iterate'],
    cta: 'Build Your MVP',
  },
  {
    slug: 'small-business',
    title: 'Small Business',
    short: 'Automation that buys back time.',
    seoTitle: 'Software & Automation for Small Businesses | AiOpsMedia',
    seoDescription: 'Small business tech: CRM, simple ERP, automation, dashboards and integrations sized for SMEs.',
    problem: 'Everything flows through the owner/founder; admin steals selling time.',
    solutions: ['Simple CRM', 'Quoting & invoicing', 'Booking & reminders', 'Reporting'],
    ai: ['Lead follow-up drafts', 'FAQ copilot'],
    automation: ['Form → CRM → follow-up → task → dashboard'],
    crmErp: ['SME bundles: CRM + automation + reports'],
    features: ['Low overhead', 'Mobile-ready', 'Support included'],
    workflow: ['Lead → quote → job → invoice → review'],
    process: ['Audit', 'Prioritise', 'Automate', 'Measure'],
    cta: 'Automate First',
  },
];

export function getIndustry(slug) {
  return industries.find((i) => i.slug === slug) || null;
}
