export const services = [
  {
    slug: 'ai-development',
    title: 'AI Development',
    short: 'Custom AI systems designed around your workflows.',
    seoTitle: 'AI Development Company | Custom AI Solutions | AiOpsMedia',
    seoDescription:
      'Custom AI development for real business problems — LLM apps, document intelligence, predictive analytics and workflow automation. Serving USA, UK, UAE worldwide.',
    icon: 'Brain',
    hero: 'Custom AI Development for Real Business Problems',
    problem: 'Businesses sit on data and repetitive decisions but generic AI tools do not fit their processes. Reports are manual, knowledge is tribal, and support/sales drown in repetition.',
    solution: 'We design AI around your workflow — RAG over your knowledge base, document intelligence, recommendation and forecasting, and AI tightly integrated with your CRM/ERP.',
    features: [
      'AI product development & LLM applications',
      'Knowledge copilots & internal search (RAG)',
      'Document intelligence & extraction',
      'Recommendation & predictive analytics',
      'Workflow intelligence & dashboards',
      'AI integrations with existing systems',
    ],
    useCases: [
      'Customer support triage & answer',
      'Sales assistance & qualification',
      'Operations document processing',
      'Education/real estate knowledge search',
      'Forecasting and anomaly detection',
    ],
    industries: ['Real Estate', 'Education', 'Healthcare', 'Professional Services', 'E-commerce', 'Retail', 'Hospitality', 'Startups'],
    process: ['Discover', 'Strategize', 'Build', 'Test', 'Launch', 'Improve'],
    deliverables: ['AI architecture & data design', 'Model/API integration', 'Evaluation harness', 'Deployment & monitoring', 'Handover & docs'],
    tech: ['Next.js', 'Node.js', 'Python', 'PostgreSQL', 'Vector DB (pgvector)', 'Groq/LLM APIs', 'Cloud Run/Vercel'],
    faqs: [
      { q: 'Do you build custom AI or wrap third-party tools?', a: 'We build custom systems around your data and workflows using LLMs, your knowledge base and business rules — not just a chatbot skin.' },
      { q: 'Can you integrate AI into existing software?', a: 'Yes. We add AI copilots, search and automation to your current CRM/ERP or web app via APIs.' },
      { q: 'How do you handle data privacy?', a: 'Data protection by design, scoped access, and deployments in your cloud where required. No training on your data without consent.' },
    ],
    related: ['ai-agents', 'ai-automation', 'custom-software-development'],
  },
  {
    slug: 'ai-agents',
    title: 'AI Agents',
    short: 'AI-powered agents for support, sales, operations and internal processes.',
    seoTitle: 'AI Agents Development Company | Custom AI Agents | AiOpsMedia',
    seoDescription:
      'AI agents that work alongside your business — support, lead qualification, appointment handling, document processing and follow-ups with human escalation.',
    icon: 'Bot',
    hero: 'AI Agents That Work Alongside Your Business',
    problem: 'Customer messages pile up across channels, leads go cold, and internal research wastes hours. Simple chatbots answer but cannot act.',
    solution: 'We build agents with tools, memory and permissions that can read your knowledge base, qualify leads, book appointments, process documents and escalate to humans when needed. Human approval stays where it matters.',
    features: [
      'Knowledge-grounded answers (RAG)',
      'Lead qualification & routing',
      'Appointment handling & reminders',
      'Document processing & data extraction',
      'Multi-channel: web, WhatsApp, internal tools',
      'Human escalation & audit trail',
    ],
    useCases: [
      'Support deflection & escalation',
      'Pre-sales qualification',
      'Appointment/visit scheduling',
      'Internal research assistant',
      'Data analysis & follow-ups',
    ],
    industries: ['Real Estate', 'Education', 'Healthcare', 'E-commerce', 'Professional Services'],
    process: ['Discover', 'Strategize', 'Build', 'Test', 'Launch', 'Improve'],
    deliverables: ['Agent architecture (LLM + tools + memory)', 'Knowledge ingestion', 'Workflow & permissions', 'Monitoring dashboard'],
    tech: ['LLM APIs', 'Vector Search', 'Next.js', 'Node.js', 'Webhooks'],
    faqs: [
      { q: 'Are agents fully autonomous?', a: 'No — they act within permissions you set and escalate to humans for high-stakes decisions. Autonomy is scoped, not absolute.' },
      { q: 'Can agents use our existing knowledge base?', a: 'Yes. We index your docs, policies and FAQs with access controls and keep answers grounded with citations.' },
    ],
    related: ['ai-development', 'ai-automation', 'crm-development'],
  },
  {
    slug: 'ai-automation',
    title: 'AI Automation',
    short: 'Connect systems and automate repetitive business processes.',
    seoTitle: 'AI Automation Services | Business Process Automation | AiOpsMedia',
    seoDescription:
      'Trigger → AI processing → rules → integrations → action → logging → human approval. Automate lead qualification, follow-ups and operations.',
    icon: 'Workflow',
    hero: 'AI Automation That Moves Work Forward',
    problem: 'Leads sit idle, tasks are copied between tools, and approvals depend on chat messages. Automation without intelligence misses nuance.',
    solution: 'We chain triggers, LLM reasoning, business rules and integrations into reliable workflows with logs and human checkpoints. Example: Lead enters CRM → AI qualifies → CRM updated → email drafted → sales notified → dashboard refreshed.',
    features: [
      'Triggers from forms, CRMs, sheets, APIs',
      'AI classification & drafting',
      'Rules, approvals and SLAs',
      'Integrations: CRM, ERP, email, WhatsApp',
      'Logging, retry and observability',
      'Human-in-the-loop where required',
    ],
    useCases: ['Lead qualification & follow-up', 'Document intake & extraction', 'Ticket routing', 'Report generation', 'Data sync across tools'],
    industries: ['Real Estate', 'Education', 'SMEs', 'Agencies', 'Startups'],
    process: ['Map flow', 'Select candidates', 'Integrate', 'Add AI', 'Add approvals', 'Measure'],
    deliverables: ['Workflow maps', 'Automation implementation', 'Integration suite', 'Runbooks'],
    tech: ['Node.js', 'REST APIs', 'Webhooks', 'PostgreSQL', 'Queue/workers'],
    faqs: [
      { q: 'What should we automate first?', a: 'High-volume, rule-based work with clear triggers — lead intake, follow-ups, status updates, report prep.' },
      { q: 'Do we need to replace our tools?', a: 'No. We integrate your existing stack and add automation on top.' },
    ],
    related: ['ai-development', 'ai-agents', 'business-process-automation'],
  },
  {
    slug: 'custom-software-development',
    title: 'Custom Software Development',
    short: 'Purpose-built software for unique business requirements.',
    seoTitle: 'Custom Software Development Company | AiOpsMedia',
    seoDescription:
      'Purpose-built software, portals, dashboards and SaaS products. Next.js, Node.js, PostgreSQL/MongoDB with secure, scalable delivery.',
    icon: 'Code2',
    hero: 'Custom Software Built Around Your Business',
    problem: 'Off-the-shelf tools force you to adapt; spreadsheets break at scale; growth exposes duct-tape workflows.',
    solution: 'We architect portals, dashboards, internal tools and SaaS from scratch — shaped by your workflows, permissions and integrations, with secure deployment and ownership.',
    features: ['Portals & dashboards', 'Role-based access & permissions', 'Integrations & APIs', 'Mobile-ready', 'SaaS readiness', 'Code ownership'],
    useCases: ['Customer portal', 'Internal tools', 'Booking system', 'SaaS MVP', 'Workflow platform'],
    industries: ['Professional Services', 'Healthcare', 'E-commerce', 'Real Estate', 'Education'],
    process: ['Discover', 'Strategize', 'Build', 'Test', 'Launch', 'Improve'],
    deliverables: ['Architecture & design', 'Web app', 'APIs & integrations', 'Deployment'],
    tech: ['Next.js', 'React', 'Node.js', 'PostgreSQL', 'MongoDB', 'REST APIs', 'Cloud'],
    faqs: [{ q: 'Custom vs off-the-shelf?', a: 'Choose custom when workflows, permissions or integrations are strategic. It costs more upfront but scales better.' }],
    related: ['web-development', 'ecommerce-development', 'crm-development'],
  },
  {
    slug: 'crm-development',
    title: 'CRM Development',
    short: 'Custom CRM platforms designed around your sales process.',
    seoTitle: 'Custom CRM Development Company | CRM Software | AiOpsMedia',
    seoDescription:
      'Custom CRM: lead management, pipeline, tasks, reports, role permissions, integrations and AI lead scoring for real estate, education, B2B and more.',
    icon: 'ContactRound',
    hero: 'Custom CRM Built Around Your Sales Process',
    problem: 'Leads leak, follow-ups lag, managers lack visibility, and generic CRMs do not reflect how you actually sell.',
    solution: 'A CRM modeled on your pipeline — contacts, tasks, calls, dashboards, permissions, reports, WhatsApp and website ingestion plus AI lead scoring.',
    features: [
      'Lead inbox & pipeline',
      'Contacts & tasks',
      'Calls, follow-ups & reminders',
      'Dashboards & reports',
      'Role permissions',
      'Integrations & AI scoring',
    ],
    useCases: ['Real estate enquiries', 'Education admissions', 'B2B sales', 'Agency pipelines'],
    industries: ['Real Estate', 'Education', 'Healthcare', 'Agencies', 'Professional Services'],
    process: ['Map pipeline', 'Design modules', 'Build', 'Integrate', 'Train', 'Iterate'],
    deliverables: ['CRM platform', 'Import & integrations', 'Training', 'Support'],
    tech: ['Next.js', 'Node.js', 'PostgreSQL', 'REST APIs', 'WhatsApp Business'],
    faqs: [{ q: 'Can you migrate from spreadsheets?', a: 'Yes. We import, dedupe and map your data, then model the CRM to your workflow.' }],
    related: ['real-estate-erp', 'ai-automation', 'business-process-automation'],
  },
  {
    slug: 'erp-development',
    title: 'ERP Development',
    short: 'Integrated systems for finance, operations, inventory and business management.',
    seoTitle: 'Custom ERP Development | AI-Powered ERP Systems | AiOpsMedia',
    seoDescription:
      'ERP for inventory, finance, HR, procurement, reporting and workflows with dashboards and AI insights. Secure, permissioned, and integrated.',
    icon: 'Boxes',
    hero: 'ERP That Runs Your Operations',
    problem: 'Inventory, finance, HR and procurement live in different places; reporting is manual and slow.',
    solution: 'A unified ERP with modules you actually need, permissioned workflows, dashboards and AI-driven insights — integrated to your sales channels and finance stack.',
    features: ['Inventory & procurement', 'Finance & payroll', 'HR & attendance', 'Workflows & permissions', 'Reports & dashboards', 'AI insights'],
    useCases: ['Retail & distribution', 'Manufacturing support', 'Services operations', 'Inventory-led businesses'],
    industries: ['Retail', 'Hospitality', 'Professional Services', 'Startups', 'SMEs'],
    process: ['Discovery', 'Module map', 'Build', 'Integrate', 'Test', 'Rollout'],
    deliverables: ['ERP modules', 'Migrations', 'Reports', 'Admin & docs'],
    tech: ['Node.js', 'PostgreSQL', 'Next.js', 'REST APIs'],
    faqs: [{ q: 'ERP vs CRM?', a: 'CRM = customer/sales. ERP = operations-wide. Many businesses need both, integrated.' }],
    related: ['school-erp', 'real-estate-erp', 'custom-software-development'],
  },
  {
    slug: 'real-estate-erp',
    title: 'Real Estate ERP',
    short: 'All-in-one platform for developers, brokers and agencies.',
    seoTitle: 'Real Estate ERP Software | CRM & Property Management | AiOpsMedia',
    seoDescription:
      'Property management, leads, agents, site visits, bookings, payments, commissions and WhatsApp integration — built for Dubai/UAE and global real estate.',
    icon: 'Building2',
    hero: 'Real Estate ERP That Turns Enquiries Into Closings',
    problem: 'Leads from portal/website/WhatsApp are scattered, assignments fail, viewings slip, and commissions are tracked in sheets.',
    solution: 'A Real Estate ERP consolidating listing, lead, agent, site visit, inventory, booking, document, payment and commission workflows with dashboard, reports and integrations.',
    features: [
      'Lead capture & assignment',
      'Property & inventory module',
      'Site visits & follow-ups',
      'Bookings, payments & commissions',
      'Documents & roles',
      'WhatsApp & website integration',
    ],
    useCases: ['Developer sales', 'Brokerage', 'Agency network'],
    industries: ['Real Estate'],
    process: ['Capture flow', 'Configure modules', 'Integrate portals', 'Train teams', 'Launch'],
    deliverables: ['Real Estate ERP', 'Portal adapters', 'Dashboards', 'Training'],
    tech: ['Next.js', 'Node.js', 'PostgreSQL', 'WhatsApp API'],
    faqs: [{ q: 'Can you integrate Bayut/Property Finder?', a: 'Concept integrations via scraping/adapters where API available, subject to platform terms and feasibility.' }],
    related: ['crm-development', 'ai-automation', 'business-process-automation'],
  },
  {
    slug: 'school-erp',
    title: 'School ERP',
    short: 'End-to-end school management and parent communication.',
    seoTitle: 'School ERP Software | School Management System | AiOpsMedia',
    seoDescription:
      'Admissions, students, fees, attendance, examinations, timetable, transport, library and notifications — a complete school ERP.',
    icon: 'GraduationCap',
    hero: 'School ERP That Runs The Whole Campus',
    problem: 'Admissions, fees, attendance and parent updates stretch staff across paper and scattered tools.',
    solution: 'A School ERP connecting admissions, student records, fees, attendance, exams, timetable, teachers, transport, library and communications with role-aware dashboards.',
    features: ['Admissions & students', 'Fees & receipts', 'Attendance & exams', 'Timetable & transport', 'Library & notifications', 'Reports'],
    useCases: ['K-12 schools', 'Colleges & coaching centres', 'Multi-branch groups'],
    industries: ['Education'],
    process: ['Map school flow', 'Configure modules', 'Import data', 'Train', 'Go-live'],
    deliverables: ['School ERP', 'Mobile-ready web', 'Reports', 'Support'],
    tech: ['Next.js', 'Node.js', 'PostgreSQL'],
    faqs: [{ q: 'Do parents get access?', a: 'Yes — parent portal for fees, attendance, Homework and announcements with notifications.' }],
    related: ['erp-development', 'web-development', 'ai-automation'],
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    short: 'Corporate sites, portals, dashboards and custom web apps.',
    seoTitle: 'Web Development Company | Next.js & Custom Web Apps | AiOpsMedia',
    seoDescription:
      'Corporate websites, SaaS platforms, portals and custom web apps with Next.js, React, Node.js, PostgreSQL/MongoDB and cloud deployment.',
    icon: 'Globe',
    hero: 'Web Applications That Scale With You',
    problem: 'Template sites cannot handle booking, portals or dashboards; performance and security lag.',
    solution: 'We build fast, accessible sites and apps — marketing site, SaaS, portal, booking or custom workflow — on proven stacks with proper DevOps.',
    features: ['Marketing sites', 'Portals & dashboards', 'Booking & SaaS', 'E-commerce', 'APIs & cloud'],
    useCases: ['Corporate site', 'Customer portal', 'SaaS MVP', 'Booking system'],
    industries: ['Professional Services', 'Hospitality', 'E-commerce', 'Education'],
    process: ['Strategy', 'Design', 'Build', 'Test', 'Launch'],
    deliverables: ['Web app', 'CMS where needed', 'APIs', 'Deploys'],
    tech: ['Next.js', 'React', 'Node.js', 'PostgreSQL', 'MongoDB', 'REST APIs', 'Cloud'],
    faqs: [{ q: 'Which stack?', a: 'Next.js, React, Node.js, PostgreSQL/MongoDB, REST APIs, Cloud — only those we actually use.' }],
    related: ['ecommerce-development', 'custom-software-development', 'seo'],
  },
  {
    slug: 'ecommerce-development',
    title: 'E-commerce Development',
    short: 'Stores, marketplaces and headless commerce.',
    seoTitle: 'E-commerce Development Company | Custom Stores | AiOpsMedia',
    seoDescription:
      'Custom e-commerce: catalog, cart, checkout, payments, inventory, CRM/ERP integration and analytics for scalable retail.',
    icon: 'ShoppingCart',
    hero: 'E-commerce Built For Conversions and Operations',
    problem: 'Generic themes limit checkout, promos and ops integrations; reporting is fragmented.',
    solution: 'We build stores that convert and operate — catalog, cart, checkout, payments, inventory sync, CRM/ERP and automation with clean analytics.',
    features: ['Catalog & inventory', 'Payments & checkout', 'Promos & reviews', 'CRM/ERP sync', 'Analytics'],
    useCases: ['DTC store', 'Marketplace', 'Subscription commerce'],
    industries: ['E-commerce', 'Retail', 'Hospitality'],
    process: ['Discovery', 'Build', 'Integrate', 'Launch', 'Optimize'],
    deliverables: ['Storefront', 'Admin', 'Integrations'],
    tech: ['Next.js', 'Node.js', 'PostgreSQL', 'Stripe/Razorpay concepts'],
    faqs: [{ q: 'Do you integrate payments?', a: 'Yes — payment gateway concepts and order-to-cash integration, compliant with gateway policies.' }],
    related: ['web-development', 'business-process-automation', 'seo'],
  },
  {
    slug: 'business-process-automation',
    title: 'Business Process Automation',
    short: 'Trigger → AI → rules → integrations → action → logs → approval.',
    seoTitle: 'Business Process Automation Services | AiOpsMedia',
    seoDescription:
      'Automate repetitive processes: form → AI classification → CRM update → task → notification → dashboard. With approvals where required.',
    icon: 'Zap',
    hero: 'Automate The Work That Slows You Down',
    problem: 'Handoffs fail, data is retyped, SLA conflicts and audits lack a trail.',
    solution: 'We map processes, instrument triggers, add rules and AI, integrate your tools, log every step and keep human approvals for high-stakes actions.',
    features: ['Process mining light', 'Workflow automation', 'Approval flows', 'Audit logs', 'Dashboards'],
    useCases: ['Lead → CRM → task', 'Invoice intake', 'Onboarding', 'Support routing'],
    industries: ['Professional Services', 'Real Estate', 'Education', 'SMEs'],
    process: ['Identify', 'Map', 'Select', 'Add AI', 'Integrate', 'Measure'],
    deliverables: ['Workflow specs', 'Automations', 'Logs & reports'],
    tech: ['Node.js', 'APIs', 'PostgreSQL'],
    faqs: [{ q: 'Where to start?', a: 'Repetitive, frequent, rule-based work with a clear trigger and outcome. We provide a checklist.' }],
    related: ['ai-automation', 'ai-agents', 'crm-development'],
  },
  {
    slug: 'social-media-management',
    title: 'Social Media Management',
    short: 'Strategy, content and performance for growth.',
    seoTitle: 'Social Media Management Services | AiOpsMedia',
    seoDescription: 'Content calendars, creative, community and reporting for LinkedIn, Instagram and Facebook — tied to pipeline where appropriate.',
    icon: 'Share2',
    hero: 'Social That Earns Attention and Pipeline',
    problem: 'Posting without strategy or reporting rarely converts.',
    solution: 'Strategy → calendar → creation → publishing → engagement → reporting, aligned to ICP and integrated with your funnels where possible.',
    features: ['Strategy & calendar', 'Content creation', 'Publishing & community', 'Reporting'],
    useCases: ['B2B LinkedIn', 'Local service growth', 'Launch campaigns'],
    industries: ['Professional Services', 'Real Estate', 'E-commerce'],
    process: ['Strategy', 'Creation', 'Publishing', 'Reporting'],
    deliverables: ['Calendar', 'Assets', 'Reports'],
    tech: ['Meta APIs concept', 'Analytics'],
    faqs: [{ q: 'Do you run ads?', a: 'Yes — see Meta Ads and Google Ads services for paid acquisition.' }],
    related: ['meta-ads', 'google-ads', 'seo'],
  },
  {
    slug: 'seo',
    title: 'SEO',
    short: 'Organic growth with technical SEO and topic clusters.',
    seoTitle: 'SEO Services | Technical & Content SEO | AiOpsMedia',
    seoDescription: 'Technical SEO, content clusters, internal linking, and performance for organic discovery — built for B2B, no keyword stuffing or doorway pages.',
    icon: 'Search',
    hero: 'SEO That Earns Qualified Traffic',
    problem: 'Beautiful sites still invisible without technical SEO, clusters and internal links.',
    solution: 'Technical audits, cluster architecture, content that solves real problems, and clean internal linking — without spam, doorways or fake signals.',
    features: ['Tech SEO', 'Content clusters', 'On-page & internal linking', 'Core Web Vitals', 'Sitemaps & schema'],
    useCases: ['New site launch', 'Stalled organic traffic', 'AI/search discovery'],
    industries: ['All B2B', 'Real Estate', 'Education'],
    process: ['Audit', 'Clusters', 'Content', 'Links', 'Measure'],
    deliverables: ['Audit', 'Plan', 'Content', 'Reports'],
    tech: ['Next.js Metadata API', 'JSON-LD', 'Search Console'],
    faqs: [{ q: 'Do you guarantee #1?', a: 'No one can. We target qualified, commercial-intent terms and build sustainably with legitimate signals.' }],
    related: ['web-development', 'google-ads', 'social-media-management'],
  },
  {
    slug: 'meta-ads',
    title: 'Meta Ads',
    short: 'Targeted acquisition on Facebook and Instagram.',
    seoTitle: 'Meta Ads Services | Facebook & Instagram Ads | AiOpsMedia',
    seoDescription: 'Meta Ads for lead generation and retargeting — compliant targeting, creative testing and conversion tracking.',
    icon: 'Megaphone',
    hero: 'Meta Ads That Drive Leads, Not Just Clicks',
    problem: 'Boosted posts waste budget without targeting, creative or landing-page fit.',
    solution: 'We align ICP, angles, creatives, landing pages and pixels, test systematically and optimize for qualified leads with proper tracking.',
    features: ['Audience & angles', 'Creative testing', 'Landing pages', 'Pixel/CAPI'],
    useCases: ['Lead gen', 'Retargeting', 'Launch'],
    industries: ['Real Estate', 'Education', 'E-commerce'],
    process: ['Strategy', 'Creation', 'Launch', 'Optimize'],
    deliverables: ['Campaigns', 'Assets', 'Reports'],
    tech: ['Meta Pixel concepts'],
    faqs: [{ q: 'Do you guarantee leads?', a: 'No guarantees. We optimize for qualified leads and report transparently.' }],
    related: ['google-ads', 'social-media-management', 'seo'],
  },
  {
    slug: 'google-ads',
    title: 'Google Ads',
    short: 'Capture high-intent search demand.',
    seoTitle: 'Google Ads Services | Search & Performance | AiOpsMedia',
    seoDescription: 'Search and performance campaigns with landing pages, conversion tracking and lead source attribution for B2B.',
    icon: 'Target',
    hero: 'Google Ads That Capture Intent',
    problem: 'Generic campaigns send high-intent traffic to generic pages and waste spend.',
    solution: 'Intent-matched keywords, dedicated landing pages per service/market, conversion and UTM tracking, and continuous optimization.',
    features: ['Intent keywords', 'Landing pages', 'Conversion tracking', 'UTM & lead source'],
    useCases: ['CRM/ERP enquiries', 'AI development leads', 'Emergency demand capture'],
    industries: ['Professional Services', 'Real Estate', 'B2B'],
    process: ['Keywords', 'Pages', 'Tracking', 'Optimize'],
    deliverables: ['Campaigns', 'Landing pages', 'Reports'],
    tech: ['Google Ads', 'GA4', 'Search Console'],
    faqs: [{ q: 'Do landing pages duplicate content?', a: 'No. Each landing page has unique, useful content — we avoid thin doorway tactics.' }],
    related: ['meta-ads', 'seo', 'web-development'],
  },
];

export function getService(slug) {
  return services.find((s) => s.slug === slug) || null;
}
export function getServiceSeo(slug) {
  const s = getService(slug);
  if (!s) return null;
  return { title: s.seoTitle, description: s.seoDescription };
}
